# Generated by Django 3.2.6 on 2021-08-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_ball', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(),
        ),
    ]
