# Generated by Django 4.0 on 2022-01-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_ball', '0003_auto_20210811_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=25),
        ),
    ]
