# Generated by Django 4.0 on 2022-01-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v_ball', '0004_alter_player_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_name',
            field=models.CharField(max_length=30),
        ),
    ]
